name: De obfuscate Java Me app and game

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:
    inputs:
      runDeob:
        description: 'Description'
        default: '*'

jobs:
   Run_PGD_forWindows_Os:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
         distribution: 'microsoft'
         java-version: '21'
    - run: ./deobfuscate.bat CiTyNikitaMobile.jar
    - uses: actions/upload-artifact@v4
      with:
          name: CiTyNikitaMobile
          compression-level: 0
          path: |  
                 CiTyNikitaMobile/*
